version: '3'

services:
  web:
    container_name: ipssi_devops
    image: remytr/ipssi_devops_final_test:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 8080:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    #networks:
    #  - backend
  redis:
    image: redis:alpine
    container_name: redis
    # volumes:
    #   - db_redis:/usr/local/etc/redis
    restart: always
    ports: 
      - 6379:6379
    #networks:
    #  - backend
# volumes:
#   db_data:
#networks:
#  backend:
#    name: ipssi_devops-backend