version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    # volumes:
    #   - db_redis:/usr/local/etc/redis
    restart: always
    ports: 
      - 6379:6379
# volumes:
#   db_data: